### ISSUE TITLE
Tag first release

### ISSUE THREAD

**Issue by nickrmc83** [eclipse-keypont/crypto11#12]
As this project has matured we should tag an initial release once symmetric crypto support has been accepted.

**Comment by nickrmc83** [comment]
Ideally we'd include a code coverage indicator/measure as generated via the CI. This would allow us to monitor new commits and areas for improvement.

**Comment by dmjones** [comment]
This is now done: https://github.com/ThalesIgnite/crypto11/releases.

v0.1.0 is the first release. There will probably be a set of breaking changes leading to a v1.0.0 release (see #36).
