### ISSUE TITLE
Generic FindKey

### ISSUE THREAD

**Issue by optnfast** [eclipse-keypont/crypto11#16]
Currently the `FindKey...` functions require you to know in advance whether you're looking for a symmetric or asymmetric key. Instead they should be independent of key type.

**Comment by nickrmc83** [comment]
IMO a sensible approach would be to keep the current  `FindXXX` functions but implement them with a subtle interface that allows for other attributes to be included in the search. Ideally we'd be able to come up with some sort of fluent-api factory which could resemble something like a C# LINQ query.

```
var search SearchFactory
key := search.From(Slot)
  .Class(Symmetric)
  .Type(AES)
  .Length(256)
  .Label("1234567")
  .First()

```

**Comment by dmjones** [comment]
Closing this issue. The redesign is being discussed in #36, which is a good place to raise any remaining ideas.

Side note - I'm struggling to imagine a use case where you don't know which type of key you are looking for...
