### ISSUE TITLE
Stop generating labels with NUL bytes at the end

### ISSUE THREAD

**Issue by dmjones** [eclipse-keypont/crypto11#31]
If users don't pass a label or ID to the key generation functions, one is generated for them. This value will typically have ~20 NUL bytes at the end, which causes problems if users convert to/from strings using `string(<some bytes>)` and `[]byte(<the string>)`. This kind of simple string conversions will discard NUL bytes, resulting in a different label or ID.

We should adjust this behaviour and return non-NUL data. I would suggest generating random bytes, converting to hexadecimal characters, then returning the bytes of that hexadecimal string.

**Comment by dmjones** [comment]
Of course, I argue strongly in #15 for us to drop key generation and I still intend to do that. But fixing this prior to deprecating those functions seems friendly.

**Comment by mrangana** [comment]
From the [pkcs11](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.pdf) spec, the label is of type string. 

Section: "4.4 Storage Objects" CKA_LABEL RFC2279 | string | Description of the object (default empty)."
