### ISSUE TITLE
go get github.com/ThalesIgnite/crypto11 exits with error

### ISSUE THREAD

**Issue by mrangana** [eclipse-keypont/crypto11#32]
$ go get github.com/ThalesIgnite/crypto11
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: proxyconnect tcp: EOF)
package vitess.io/vitess/go/cache: unrecognized import path "vitess.io/vitess/go/cache" (https fetch: Get https://vitess.io/vitess/go/cache?go-get=1: proxyconnect tcp: EOF)
package vitess.io/vitess/go/sync2: unrecognized import path "vitess.io/vitess/go/sync2" (https fetch: Get https://vitess.io/vitess/go/sync2?go-get=1: proxyconnect tcp: EOF)
package vitess.io/vitess/go/timer: unrecognized import path "vitess.io/vitess/go/timer" (https fetch: Get https://vitess.io/vitess/go/timer?go-get=1: proxyconnect tcp: EOF)

**Comment by dmjones** [comment]
I can't reproduce this at my end. I did:

```
$ go version
go version go1.11.2 linux/amd64
$ cd /tmp
$ mkdir go
$ GOPATH=/tmp/go/ go get github.com/ThalesIgnite/crypto11
```
and it worked for me.

Based on your error message, perhaps your proxy settings are wrong. See https://stackoverflow.com/questions/50616909/go-get-fails-with-unrecognized-import-path-after-upgrading-to-go-1-10.

**Comment by mrangana** [comment]
Thanks for the pointer.
