### ISSUE TITLE
Panic due to misaligned atomic variables

### ISSUE THREAD

**Issue by techninja1008** [eclipse-keypont/crypto11#35]
In the dependency vitessio/vitess, a panic is caused on certain architectures due to misaligned variables. This will be fixed by vitessio/vitess#4729. When this is merged, the dependency will need to be re-vendored.

**Comment by dmjones** [comment]
Thanks for the heads up 👍

**Comment by techninja1008** [comment]
The upstream has been merged, so it would be good if we could vendor it? Should I submit a pull request, or leave it to @dmjones ?

**Comment by dmjones** [comment]
@techninja1008 Sorry for the slow response, just back in the office. A PR would be very welcome, thanks!
