### ISSUE TITLE
Add ...WithAttributes functions

### ISSUE THREAD

**Issue by dmjones** [eclipse-keypont/crypto11#41]
As part of the v1 rewrite discussions (see #36), it was suggested to add `...WithAttributes` variants of the key generation functions. This would allow generation of keys with arbitrary attributes.

I began implementing this in the `with-attributes` branch, but decided to pause the work. It's not clear if anyone using this library needs that functionality, so it feels premature to add it.

I'll leave this issue open as a reminder of the potential feature and to see if anyone has interest in it.

**Comment by jls5177** [comment]
I'm currently working on a project that needs to generate new keys with the `CKA_PRIVATE` attribute set to ensure they can only be accessed with either a OCS or a Softcard.  This proposal would work for this solution but looking at the current branch it might be too generic (requiring the caller to also add any labels and ids along with the additional parameters). I will spend some time looking at your proposed changes and see what I can come up with.
