### ISSUE TITLE
RFE: converting pkcs11.ObjectHandle to KeyPair

### ISSUE THREAD

**Issue by art-vasilyev** [eclipse-keypont/crypto11#43]
Currently, I use `miekg/pkcs11` for working with certificates and part of your code for converting loaded `privHandle` and `pubHandle` (pkcs11.ObjectHandle) into `crypto.Signer`. It would be nice to have a function like:
```
func (c *Context) BuildKeyPair(pubHandle *pkcs11.ObjectHandle, privHandle *pkcs11.ObjectHandle) (Signer, error)
```
I may try to implement this function if it doesn't contradict the project's idea

**Comment by art-vasilyev** [comment]
Didn't see there is already pull request with certificates support, that would solve my problem

**Comment by dmjones** [comment]
Indeed, we plan to update that PR and merge in shortly.
