### ISSUE TITLE
Cannot initialize more than one slot with a PKCS DLL

### ISSUE THREAD

**Issue by jls5177** [eclipse-keypont/crypto11#47]
**Problem**
I have a usecase where I need to access 2 slots ("accelerator" and an OCS) within the same application (a long running service) to be able to access module protected (any public objects) keys and private (OCS protected) keys.

**Root Cause**
The issue is due to the way the PKCS11 module loads a given DLL as it does not provide any guards to prevent a user from calling `New()` multiple times for the same DLL. 

**Possible Fixes**
The PKCS11 module already solved this issue in their [P11 submodule](https://github.com/miekg/pkcs11/blob/master/p11/module.go#L71..L99). We can do one of the following:
1. We can mirror what the PKCS11 P11 module does and provide a singleton object that tracks a `Module` which will only load a DLL file once. 

1. Just use the P11 module for the configuration process

Option 1 seems like the simplest solution and would require the least amount of code changes. I am willing to put up a pull request but wanted to make sure we aligned on the best solution.

**Comment by dmjones** [comment]
Yikes, thanks for spotting this. And shame on me for not catching this with a better CI setup. 

I will look at this tomorrow and will prioritise a release to fix it.

**Comment by dmjones** [comment]
I've just released v1.0.2 to address this. Thanks again for spotting it.

I've added a basic test that validates this works correctly. Ideally the CI would use several different types of token at once, but this isn't implemented right now.
