### ISSUE TITLE
pools.NewResourcePool function signature divergence

### ISSUE THREAD

**Issue by clover-bt** [eclipse-keypont/crypto11#56]
NewResourcePool from the github.com/vitessio/vitess/go/pools module is called from https://github.com/ThalesIgnite/crypto11/blob/8367a3ec46bf7e0250f82f1e1c3a45bc43e9112f/crypto11.go#L320. However, the function signature does not match https://github.com/vitessio/vitess/blob/b5eb51a6b17f17af8b2002187fdaf653ef47cf96/go/pools/resource_pool.go#L88, which appears to have changed May 2019: https://github.com/vitessio/vitess/commit/9cebb4079b7beee9f327a6a470d310a03ed9538d#diff-0f7dd748d05e2a8a4b9295ff9bfc3c3a.

**Comment by dmjones** [comment]
You are not the first to mention this: #51

I believe we are tripping over the way Go treats packages that are tagged v2.0.0 or higher, but don't use modules ([reference](https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-v2-package-that-has-not-opted-into-modules-what-does-incompatible-mean)). Go makes a sweeping assumption that semver is not in use and treats every version as backwards compatible.

So if you have run `go get github.com/vitessio/vitess` in your project, or if another dependency relies on vitess v3, Go will assume it's all compatible.

The short fix answer is probably to rekindle #51 and update to v3.x of vitess.

The longer fix, which I'll open an issue for, should be to clone the interesting parts of vitess and make it available as a separate Go module in Github. It was a very heavy dependency just to get a resource pool implementation.
