### ISSUE TITLE
SECP256K1 Support

### ISSUE THREAD

**Issue by lmahanand** [eclipse-keypont/crypto11#63]
Does it supports curve secp256k1 to be used in AWS Cloud HSM? If it is, then could you please tell me as to what exactly the curve name I need to pass?

Below are the curve details, I am using:

```
curve := elliptic.P256()
crypto.SHA256 // hash function

```

**Comment by lmahanand** [comment]
> Does it supports curve secp256k1 to be used in AWS Cloud HSM? If it is, then could you please tell me as to what exactly the curve name I need to pass?
> 
> Below are the curve details, I am using:
> 
> ```
> curve := elliptic.P256()
> crypto.SHA256 // hash function
> ```

Closing this issue. I am able to sign with secp256k1. The issue was with incorrect use of ASN object id of secp256k1.

**Comment by siddhartpai** [comment]
@lmahanand I know this is a long closed thread. It would help if you could elaborate on how you got it to work with secp256k1. 

elliptic.P256 implements secp256r1 not k1. 
crypto.S256 implements secp256k1
