### ISSUE TITLE
Access to attributes (CKA_*)

### ISSUE THREAD

**Issue by printmaps** [eclipse-keypont/crypto11#88]
Is it somehow possible to access the attributes of an object? E.g. the attributes CKA_ID and CKA_LABEL of a certificate.

**Comment by maraino** [comment]
Yes, you can use [Context.GetAttributes](https://pkg.go.dev/github.com/ThalesIgnite/crypto11#Context.GetAttributes):
```go
attrs, err := ctx.GetAttributes(key, []uint{crypto11.CkaId, crypto11.CkaLabel})
```

**Comment by printmaps** [comment]
Thanks for looking into issue. I want to get access to the attributes of a certificate. But that doesn't seem to be possible at the moment.
