### ISSUE TITLE
ecdsa.unmarshalEcPoint expects ASN.1 data, but should be raw

### ISSUE THREAD

**Issue by jeajjr** [eclipse-keypont/crypto11#94]
Hello! I've encountered this issue while integrating the library with an HSM.

It seems that `ecdsa.unmarshalEcPoint` expects an ASN.1 encoded EC Point, but from what I've understood from PKCS#11 spec on CKA_EC_POINT ([link](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/os/pkcs11-curr-v2.40-os.html), see section 2.3.3), it should only be a "DER-encoding of ANSI X9.62 ECPoint", which would not contain a ASN.1 header. The absence of the ASN.1 header makes `ecdsa.unmarshalEcPoint` fail when it calls `asn1.Unmarshal`.

I thank you in advance for your attention.

**Comment by optnfast** [comment]
The intended representation is to compute 04 || X || Y to form an octet-string, and then generate the DER encoding of that octet string. So an example point on P256 would be:

```
0x04, 0x41,
0x04,
0x23, 0x35, 0x5C, 0x78, 0x3A, 0xB3, 0xD5, 0x6B, 0x9A, 0xDD, 0x7B, 0xDF, 0x70, 0xF6, 0x34, 0x47, 0x5F, 0x34, 0xEA, 0x17, 0x70, 0xB0, 0x70, 0x2F, 0x83, 0x4F, 0xB9, 0xD8, 0xA1, 0xBC, 0x03, 0xD1,
0x55, 0xBE, 0xFF, 0xCB, 0xF5, 0x16, 0x39, 0xA5, 0xF9, 0x8C, 0x80, 0x91, 0xEB, 0xDB, 0x5D, 0x5C, 0xA5, 0x1C, 0xE4, 0xB2, 0x6E, 0x13, 0x41, 0x54, 0x1C, 0xD1, 0xAC, 0x01, 0xF1, 0x67, 0xA7, 0xE1
```

I don't have a working crypto11 setup right now but https://go.dev/play/p/ovs3_k3-Q3i shows that essentially the same code will parse this point OK.

It sounds like you think the initial 0441 should not be there. But that would just be the X9.62 encoding, without any DER at all. That does not make sense as an interpretation of the spec.

**Comment by jeajjr** [comment]
I apologize, I totally overlooked that DER encoding demands those initial bytes. Thank you!
